---

- name: copy filebeat ILM policy
  template:
    src: 'ilm_policy.json.j2'
    dest: '/etc/filebeat/ilm_policy.json'
    mode: 0644
    owner: root
    group: root

- name: set up filebeat log monitoring
  include_role:
    name: elastic.beats
  vars:
    beat: filebeat
    beat_conf:
      setup:
        template:
          name: logs-drive-abci-%{[agent.version]}
          pattern: logs-drive-abci-%{[agent.version]}-*
          append_fields:
            - name: json.stateRepository.params
              type: object
              dynamic: runtime
            - name: json.stateRepository.response
              type: object
              dynamic: runtime
            - name: json.abciRequest
              type: object
              dynamic: runtime
            - name: json.errors
              type: nested
              dynamic: runtime
            - name: json.height
              type: long
            - name: json.err
              type: object
              dyanmic: runtime
          settings:
            index:
              sort:
                field:
                  - json.height
                  - json.abciMethod
                  - json.level
                order:
                  - asc
                  - asc
                  - asc
        ilm:
          policy_file: /etc/filebeat/ilm_policy.json
          rollover_alias: "logs-drive-abci"
          policy_name: "masternode-logs"
      filebeat:
        inputs:
          - type: log
            enabled: true
            json.message_key: msg
            json.keys_under_root: false
            exclude_files: ['\.gz$']
            index: "logs-drive-abci-%{[agent.version]}"
            paths:
              - "{{ mn_evo_services_path }}/logs/*.log*"
            processors:
              - timestamp:
                  field: json.time
                  layouts:
                    - UNIX_MS
              - if:
                  equals:
                    json.level: 10
                then:
                  - add_fields:
                      target: log
                      fields:
                        level: trace
              - if:
                  equals:
                    json.level: 20
                then:
                  - add_fields:
                      target: log
                      fields:
                        level: debug
              - if:
                  equals:
                    json.level: 30
                then:
                  - add_fields:
                      target: log
                      fields:
                        level: info
              - if:
                  equals:
                    json.level: 40
                then:
                  - add_fields:
                      target: log
                      fields:
                        level: warn
              - if:
                  equals:
                    json.level: 50
                then:
                  - add_fields:
                      target: log
                      fields:
                        level: error
              - if:
                  equals:
                    json.level: 60
                then:
                  - add_fields:
                      target: log
                      fields:
                        level: fatal
              - add_fields:
                  target: event
                  fields:
                    dataset: "drive-abci.log"
              - rename:
                  fields:
                    - from: "json.msg"
                      to: "message"
                  ignore_missing: true
                  fail_on_error: true
              - drop_fields:
                  fields:
                    - json.pid
                    - json.hostname
                    - json.time
                  ignore_missing: true
    output_conf:
      elasticsearch:
        hosts:
          - "{{ hostvars['log'].private_ip }}:9200"
        username: "{{ elastic_username }}"
        password: "{{ elastic_password }}"
    logging_conf:
      level: info
      files:
        rotateeverybytes: 10485760
