---

- name: set up filebeat log monitoring
  include_role:
    name: elastic.beats
  vars:
    beat: filebeat
    beat_conf:
      filebeat:
        inputs:
          - type: log
            enabled: true
            paths:
              - "{{ mn_evo_services_path }}/logs/*.log*"
      processors:
        - timestamp:
            field: json.time
            layouts: 
              - UNIX_MS
        - if:
            equals:
              json.level: 10
          then:
          - add_fields:
              target: log
              fields:
                level: trace
        - if:
            equals:
              json.level: 20
          then:
          - add_fields:
              target: log
              fields:
                level: debug
        - if:
            equals:
              json.level: 30
          then:
          - add_fields:
              target: log
              fields:
                level: info
        - if:
            equals:
              json.level: 40
          then:
          - add_fields:
              target: log
              fields:
                level: warn
        - if:
            equals:
              json.level: 50
          then:
          - add_fields:
              target: log
              fields:
                level: error
        - if:
            equals:
              json.level: 60
          then:
          - add_fields:
              target: log
              fields:
                level: fatal
        - add_fields:
            target: event
            fields:
              dataset: "drive.log"
    output_conf: {
      "elasticsearch": {
        "hosts": ["{{ hostvars['web-1'].private_ip }}:9200"],
        "username": "{{ elk_elasticsearch_username }}",
        "password": "{{ elk_elasticsearch_password }}",
      }
    }
