---

- name: copy filebeat ILM policy
  template:
    src: 'ilm_policy.json.j2'
    dest: '/etc/filebeat/ilm_policy.json'
    mode: 0644
    owner: root
    group: root

- name: set up filebeat log monitoring
  include_role:
    name: elastic.beats
  vars:
    beat: filebeat
    beat_conf:
      setup:
        template:
          settings:
            index:
              sort.field: 
                - json.height
                - json.abciMethod
                - json.level
              sort.order: 
                - asc
                - asc
                - asc
          name: drive-abci
          pattern: drive-abci-*
          append_fields:
            - name: stateRepository.params
              type: object
              dynamic: runtime
            - name: stateRepository.response
              type: object
              dynamic: runtime
            - name: abciRequest
              type: object
              dynamic: runtime
            - name: errors
              type: nested
              dynamic: runtime
            - name: height
              type: long
            - name: err
              type: object
              dyanmic: runtime
        ilm:
          policy_file: /etc/filebeat/ilm_policy.json
      filebeat:
        inputs:
          - type: log
            enabled: true
            json.message_key: msg
            json.keys_under_root: true
            exclude_files: ['\.gz$']
            paths:
              - "{{ mn_evo_services_path }}/logs/*.log*"
      processors:
        - timestamp:
            field: json.time
            layouts: 
              - UNIX_MS
        - if:
            equals:
              json.level: 10
          then:
          - add_fields:
              target: log
              fields:
                level: trace
        - if:
            equals:
              json.level: 20
          then:
          - add_fields:
              target: log
              fields:
                level: debug
        - if:
            equals:
              json.level: 30
          then:
          - add_fields:
              target: log
              fields:
                level: info
        - if:
            equals:
              json.level: 40
          then:
          - add_fields:
              target: log
              fields:
                level: warn
        - if:
            equals:
              json.level: 50
          then:
          - add_fields:
              target: log
              fields:
                level: error
        - if:
            equals:
              json.level: 60
          then:
          - add_fields:
              target: log
              fields:
                level: fatal
        - add_fields:
            target: event
            fields:
              dataset: "drive.log"
    output_conf: {
      "elasticsearch": {
        "hosts": ["{{ hostvars['web-1'].private_ip }}:9200"],
        "username": "{{ elk_elasticsearch_username }}",
        "password": "{{ elk_elasticsearch_password }}",
        "index": "drive-abci"
      }
    }
