---

- name: create masternode elastic services dir
  file:
    path: '{{ elastic_path }}'
    state: directory
    recurse: true

- name: copy files
  template:
    src: '{{ item }}.j2'
    dest: '{{ elastic_path }}/{{ item }}'
  loop:
    - docker-compose.yml
    - elasticsearch.yml
    - kibana.yml
    - logstash.yml
    - logstash.conf

- name: start elastic services
  docker_compose:
    project_src: '{{ elastic_path }}'
    state: present
    restarted: yes
    pull: yes
